services:
  usuario:
    build:
      context: https://github.com/Fiap-Pos-Tech-Arquitetura-Java/HackaPay-Usuario.git
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:postgresql://usuario-db:5432/user-db
      - SPRING_DATASOURCE_USERNAME=hackaPay
      - SPRING_DATASOURCE_PASSWORD=hackaPayUser
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - logging.level.org.springframework.web=TRACE
      - org.springframework.cloud.config=DEBUG
      - logging.level.org.apache.http=DEBUG
    networks:
      - network
    restart: always
    depends_on:
      - usuario-db

  usuario-db:
    image: postgres:latest
    command: -p 5432
    environment:
      POSTGRES_DB: user-db
      POSTGRES_USER: hackaPay
      POSTGRES_PASSWORD: hackaPayUser
    networks:
      - network

  cliente:
    build:
      context: https://github.com/Fiap-Pos-Tech-Arquitetura-Java/HackaPay-Cliente.git
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cliente-db:5433/cliente-db
      - SPRING_DATASOURCE_USERNAME=hackaPay
      - SPRING_DATASOURCE_PASSWORD=hackaPayCliente
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - network
    restart: always
    depends_on:
      - cliente-db

  cliente-db:
    image: postgres:latest
    command: -p 5433
    environment:
      POSTGRES_DB: cliente-db
      POSTGRES_USER: hackaPay
      POSTGRES_PASSWORD: hackaPayCliente
    networks:
      - network

  cartao:
    build:
      context: https://github.com/Fiap-Pos-Tech-Arquitetura-Java/HackaPay-Cartao.git
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cartao-db:5434/cartao-db
      - SPRING_DATASOURCE_USERNAME=hackaPay
      - SPRING_DATASOURCE_PASSWORD=hackaPayCartao
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - network
    restart: always
    depends_on:
      - cartao-db

  cartao-db:
    image: postgres:latest
    command: -p 5434
    environment:
      POSTGRES_DB: cartao-db
      POSTGRES_USER: hackaPay
      POSTGRES_PASSWORD: hackaPayCartao
    networks:
      - network

  pagamento:
    build:
      context: https://github.com/Fiap-Pos-Tech-Arquitetura-Java/HackaPay-Pagamento.git
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pagamento-db:5435/pagamento-db
      - SPRING_DATASOURCE_USERNAME=hackaPay
      - SPRING_DATASOURCE_PASSWORD=hackaPayPagamento
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - network
    restart: always
    depends_on:
      - pagamento-db

  pagamento-db:
    image: postgres:latest
    command: -p 5435
    environment:
      POSTGRES_DB: pagamento-db
      POSTGRES_USER: hackaPay
      POSTGRES_PASSWORD: hackaPayPagamento
    networks:
      - network

  gateway:
    build:
      context: .
    ports:
      - "8084:8084"
    networks:
      - network
    restart: always
    depends_on:
      - usuario
      - cliente
      - cartao
      - pagamento

networks:
  network: